### ISSUE TITLE
overwriting `stream` class inside loop

### ISSUE THREAD

**Issue by mikowals** [elidoran/cosmos-browserify#1]
Very cool package.  Thanks.

I notice that at line [12 of plugin/browserify.js](https://github.com/elidoran/cosmos-browserify/blob/master/plugin/browserify.coffee#L12) you assign a new value to the `stream` variable which is meant to hold the Stream class from NPM and is originally declared in line 2.  This errors if your handler function gets called a more than once, i.e. when there is a second `browserify.js` source file.

**Comment by elidoran** [comment]
Thank you for pointing that out. I fixed it and published a new version to atmosphere.

**Comment by mikowals** [comment]
Thanks.
