### ISSUE TITLE
No plugin known to handle file 'app.browserify.options.json'

### ISSUE THREAD

**Issue by ubald** [elidoran/cosmos-browserify#15]
Following the example for the use in packages and using meteor devel I get this:

```
While building package foo:
error: No plugin known to handle file 'foo.browserify.options.json'. If you want this file to be a static asset, pass the {isAsset: true} option to api.addFiles; eg, api.addFiles('foo.browserify.options.json', 'client', {isAsset: true}).
```

**Comment by elidoran** [comment]
add the options file using `api.addFiles()` for `client`.

I'll update the README. thank you

**Comment by ubald** [comment]
I'm sorry, I later realized meteor was running with old versions of every package for some reason. It works correctly once the versions are up to date. Thanks though!
