### ISSUE TITLE
Sometimes cosmos:browserify freezes (loads forever?).

### ISSUE THREAD

**Issue by trusktr** [elidoran/cosmos-browserify#17]
For example, I'll see this in my console:

``` js
> meteor
[[[[[ ~/src/nowgoin+mobile_cordova/meteor-app ]]]]]

=> Started proxy.
=> Started MongoDB.
   Loading plugin `CosmosBrowserify` fro...  \
```

and it'll stay there forever. I'm not sure if that's Meteor's fault of cosmos:browserify since it says "Loading plugin `CosmosBrowserify` fro...  \" so I guess it might be Meteor loading the plugin, and the plugin isn't doing anything yet. But just posting here just in case.

**Comment by trusktr** [comment]
My CPU goes to 100% and stays there.

**Comment by trusktr** [comment]
I posted here too, just in case: https://github.com/meteor/meteor/issues/5177

**Comment by trusktr** [comment]
Note: My app isn't directly using cosmos:browserify. Some Meteor packages are (I think packages relating to React).

**Comment by trusktr** [comment]
I believe that package that is depending on cosmos:browserify is some dependency of the `react-meteor-data` package. I'm on Meteor `1.2-rc.12`.

**Comment by trusktr** [comment]
It's been loading for like 20 minutes.

**Comment by elidoran** [comment]
Are you using the [meteor-1.2-api](https://github.com/elidoran/cosmos-browserify/tree/meteor-1.2-api) branch of browserify? If not, please do so and let me know. I'd like some feedback on it beyond my own testing. 

If you are using it, please, give me some more specifics, like, which packages are you loading? If I can recreate it hanging like that I can work on figuring it out. :)

**Comment by trusktr** [comment]
@elidoran Yeah, I was on `1.2-rc.12` when this was happening. But I just downgraded to `PLUGINS-PREVIEW@2` and it's still happening.

**Comment by trusktr** [comment]
Oh, not the branch. Misread. Let me try.

**Comment by trusktr** [comment]
Seems like deleting `~/.meteor` and my app's `.meteor/local` got us past this problem, and now I've been on

```
[[[[[ ~/src/nowgoin+mobile_cordova/meteor-app ]]]]]

=> Started proxy.
=> Started MongoDB.
   Processing files with templating (for...  -
```

for 10 minutes. I wonder what is going on here.

**Comment by elidoran** [comment]
Now that Meteor 1.2 is officially released, please try cosmos:browserify@0.7.0 (made for Meteor 1.2) and see how it goes.

**Comment by khacluan** [comment]
@elidoran @trusktr 
still `Loading plugin `CosmosBrowserify` fro...  \` after upgrade to `cosmos:browserify@0.7.0`

**Comment by paulshir** [comment]
I was having the same issue. I don't actually think it is an issue with CosmosBrowserify.

I am using webpack and the outputted js file was over 2MB big. I found this issue https://github.com/meteor/meteor/issues/5198 so removed the ecmascript package (doing this conversion in webpack) and also started minifying my code.

The problem has since gone away. Hope this helps you also.

**Comment by elidoran** [comment]
@trusktr @khacluan Still having trouble, or, may I close this issue?

**Comment by trusktr** [comment]
We can close. I can re-open if it happens again.

**Comment by trusktr** [comment]
@elidoran Someone else may have experienced this same issue: https://forums.meteor.com/t/seriously-you-need-to-fix-your-build-system/15309/14?u=joe

**Comment by kevinchiu** [comment]
I am experiencing this issue after expanding the size of a javascript file in my project (which holds a large json array).

**Comment by leijing7** [comment]
I had the same issue after I put a 2M js file in the client directory.

**Comment by aaronjudd** [comment]
I experience this on a regular basis (Meteor 1.2.1). It seems to occur when I've restarted the build process mid stream while browserify (0.9.3) was being loaded. the issue is very bad while building / using velocity for tests, but I don't see it in production or regular dev builds.  It feels like the package is getting corrupted, but haven't investigated further.

**Comment by akinnee** [comment]
I'm experiencing this after adding and then removing https://atmospherejs.com/universe/react-bootstrap

**Comment by mkarliner** [comment]
I'm getting after installing ahref:dragula

**Comment by logvik** [comment]
I just have resolved it by renaming from .meteor to _.meteor, then ran in console
meteor create ./
and copy paste 

```
.finished-upgraders
packages
platforms
release
versions
```

The problem is in old build info from .meteor
May be it will help for somebody.
