### ISSUE TITLE
Can use it to browse/access client side local filesystem?

### ISSUE THREAD

**Issue by green-coder** [elidoran/cosmos-browserify#27]
Hi, can we use this plugin to browse/access the client's computer filesystem via Nodejs's fs API?

**Comment by elidoran** [comment]
This tool is a wrapper around http://browserify.org to bundle npm modules into a file which can be loaded into a browser.

To read what it does to uses of node's core modules please read their website: [npm core module compatibility](https://github.com/substack/node-browserify#compatibility).

I don't see _fs_ mentioned there. And, that makes sense. It would need to do a lot of work to get out of the browser's sandbox and get access to the client machine. 

You'll likely want to search for a JS module which does that. It will likely be made for the browser and not require being browserified before sending it to the browser.

**Comment by green-coder** [comment]
Sorry, I forgot to mention an important detail, I am hoping to run the client from inside Electron, as a desktop app, not from inside a browser. But thank you for the answer, that's clear enough on what can be done or not.
