### ISSUE TITLE
Write in JavaScript

### ISSUE THREAD

**Issue by arunoda** [elidoran/cosmos-browserify#3]
I know this is super annoying request. 
I feel very comfortable if you write this in JS :)

**Comment by elidoran** [comment]
I understand the sentiment. I often look at JavaScript code and think "why don't they write in CoffeeScript?". It's more difficult to read the language we don't write in.

I greatly prefer CoffeeScript. However, my CS source was in need of a cleanup. So, I reformatted the [source code](https://github.com/elidoran/cosmos-browserify/blob/master/plugin/browserify.coffee) with lots more whitespace and comments, and split up some of the lines. I hope this makes it easier to read for everyone, including JS writers.
