### ISSUE TITLE
Remove coffeescript

### ISSUE THREAD

**Issue by vladshcherbin** [elidoran/cosmos-browserify#30]
I don't understand you, people. One file, 100 lines of code (w/o comments), why do you bring coffeescript to our projects and build process.

Can you upgrade it with normal es2015 js please?

**Comment by elidoran** [comment]
[browserify.coffee](https://github.com/elidoran/cosmos-browserify/blob/master/plugin/browserify.coffee) is 200 lines of code, 50% of the file is comments.

You bring it to your project and build process. You may choose to avoid using all open source projects containing CoffeeScript.

ES2015 is a badly designed step towards making JavaScript into CoffeeScript.

This is all open source with an MIT license. You may fork it, transpile it to JS, change it to ES2015 syntax, and publish a JS version. I'll keep using CoffeeScript.

**Comment by vladshcherbin** [comment]
@elidoran I didn't choose to use it my projects, it comes with the other packages like react-layout or flow-router. It is just disrespectful to force our projects have coffeescript even if we don't want it.
