### ISSUE TITLE
Use packages that expose API with ES6 module system (import)

### ISSUE THREAD

**Issue by dearlordylord** [elidoran/cosmos-browserify#34]
Currently I have `"fixed-data-table": "0.6.0"` in packages.json. If I `import` API like they say in package readme - `import {Table, Column, Cell} from 'fixed-data-table';` I have an error `'import' and 'export' may appear only with 'sourceType: module'`. Any hints here? Is it supported currently? I see more and more packages that expose API like that with latest versions which renders them unusable.

**Comment by dearlordylord** [comment]
I added 

```
"es6-modules-commonjs": {

    }
```

to my *.options.json

and required it in packages.json as `"es6-modules-commonjs": "0.1.3",`

then `FixedDataTable = require('fixed-data-table');` in app.browserify.js. Works fine.

**Comment by yubozhao** [comment]
@Firfi Where exactly did you add es6-modules-commonjs inside .options.json file?  

Thanks

**Comment by dearlordylord** [comment]
@yubozhao my .options.js looks like this

```
{
  "transforms": {
    "exposify": {
      "global": true,
      "expose": {
        "react": "React",
        "react-dom": "ReactDOM"
      }
    },
    "es6-modules-commonjs": {

    }
  }
}
```
