### ISSUE TITLE
Can we import `less` files from npm package?

### ISSUE THREAD

**Issue by veeramarni** [elidoran/cosmos-browserify#42]
I'm wondering if there is a way to import `less` files that comes with npm for example `react-container` npm package has a `container.less` which i would like to import.

For my app, since i need to import many of those less files from different npm packages, i have created a meteor package with `package.import.less` file. In that file i added line something like below. 

`@import ".npm/package/node_modules/react-container/less/component.less";`

And in `package.js`, i added something like below  to use it in target App.

`api.addFiles('package.import.less', 'client');`

`package.browserify.js` with
`
Container=require("react-container");`

But the app fails to starts as the reference path stated in `@import` which points to npm folder is not found in client side. How to fix it?

**Comment by elidoran** [comment]
Have you tried getting the file like this:

``` javascript
api.addFiles('.npm/package/node_modules/react-container/less/component.less', 'client')
```

And, did you add `less` to that package so it will handle less files?

**Comment by veeramarni** [comment]
After using `api.addFiles` to add the files, it is working.
