### ISSUE TITLE
‘''Failed to parse SourceMap: http://localhost:3000/packages/3stack:bignumber/bignumber.browserify.js'''

### ISSUE THREAD

**Issue by alanwunsche** [elidoran/cosmos-browserify#49]
Running into this issue 1.4.1

Believed to be arising through a depency of the ethereum:tools package and https://atmospherejs.com/ethereum/tools in 3stack:bignumber

Can any please help with this?

**Comment by elidoran** [comment]
If you mean Meteor 1.4.1, then, there's no reason to use cosmos:browserify. Meteor 1.4.1 can handle npm modules on its own.

I looked at 3stack:bignumber and they are using cosmos:browserify version 0.4.0, the newest is 0.10.0. So, they haven't updated in a while and need to update cosmos:browserify if they're going to continue using it, and, they should update to use npm modules directly for Meteor 1.4.1.

For your immediate needs, you could fork, clone, and customize those packages to bring them up to date.
